on: push
name: FTPDeployServerPush
jobs:
  web-deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 192.168.1.252
        username: ftpUser
        password: ftppassword
        local-dir: ./
        server-dir: /var/www/busstider.com/
